name: fersys
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1
  tflite_flutter: ^0.10.1
  get: 4.6.5
  mysql1: ^0.20.0
  auto_size_text: 3.0.0
  built_collection: 5.1.1
  built_value: 8.4.3
  cached_network_image: 3.2.1
  dropdown_button2: 2.0.0
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  json_path: 0.4.1
  json_serializable: 6.6.1
  page_transition: 2.0.4
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  shared_preferences: 2.0.15
  sqflite: 2.2.0+2
  timeago: 3.2.2
  url_launcher: 6.1.5
  flutter_screenutil: ^5.7.0
  cupertino_icons: ^1.0.2
  http: any
  xml: ^6.1.0
  xml2json: ^5.3.5
  weather_icons: ^3.0.0
  fluttertoast:
  bmkg_open_data: ^1.0.1
  datepicker_dropdown: ^0.0.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  built_value_generator: 8.4.3
  flutter_launcher_icons: 0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  #assets:
   # - assets/images/


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\model.tflite
    - assets\model_fix.tflite
    - assets\model1.tflite
    - assets\model_1.tflite
    - assets\images\fersys-logo.png
    - assets\images\user.png
    - assets\images\add-user.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:yaml
# To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts\WorkSans-Black.ttf
        - asset: fonts\WorkSans-Black.ttf
        - asset: fonts\WorkSans-BlackItalic.ttf
        - asset: fonts\WorkSans-Bold.ttf
        - asset: fonts\WorkSans-BoldItalic.ttf
        - asset: fonts\WorkSans-ExtraBold.ttf
        - asset: fonts\WorkSans-ExtraBoldItalic.ttf
        - asset: fonts\WorkSans-ExtraLight.ttf
        - asset: fonts\WorkSans-ExtraLightItalic.ttf
        - asset: fonts\WorkSans-italic-vf.ttf
        - asset: fonts\WorkSans-Italic.ttf
        - asset: fonts\WorkSans-Italic[wght].ttf
        - asset: fonts\WorkSans-Light.ttf
        - asset: fonts\WorkSans-LightItalic.ttf
        - asset: fonts\WorkSans-Medium.ttf
        - asset: fonts\WorkSans-MediumItalic.ttf
        - asset: fonts\WorkSans-Regular.ttf
        - asset: fonts\WorkSans-roman-vf.ttf
        - asset: fonts\WorkSans-SemiBold.ttf
        - asset: fonts\WorkSans-SemiBoldItalic.ttf
        - asset: fonts\WorkSans-Thin.ttf
        - asset: fonts\WorkSans-ThinItalic.ttf
        - asset: fonts\WorkSans[wght].ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
